In [7]:
#Copy and view in numpy
import numpy as np
arr1 = np.array([21,24,28,4,6,3])
print("arr1:",arr1)
arr2 = np.array([1,2,3,4,5,6])
print("arr2:",arr2)
co = arr1.copy()
print("co:",co)
vi = arr2.view()
print("vi:",vi)
#making changes in orignal array
print("making changes in orignal array:")
arr1[2] = 9
print("new arr1 :",arr1)
print("new co:",co)
arr2[2]=9
print("new arr2 :",arr2)
print("new vi:",vi)
#making changes in copy and view of array
print("making changes copy and view of array:")
co[0]=0
print("new arr1-1 :",arr1)
print("new co 1:",co)
vi[0]=0
print("new arr2-1 :",arr2)
print("new vi 1:",vi)





arr1: [21 24 28  4  6  3]
arr2: [1 2 3 4 5 6]
co: [21 24 28  4  6  3]
vi: [1 2 3 4 5 6]
making changes in orignal array:
new arr1 : [21 24  9  4  6  3]
new co: [21 24 28  4  6  3]
new arr2 : [1 2 9 4 5 6]
new vi: [1 2 9 4 5 6]
making changes copy and view of array:
new arr1-1 : [21 24  9  4  6  3]
new co 1: [ 0 24 28  4  6  3]
new arr2-1 : [0 2 9 4 5 6]
new vi 1: [0 2 9 4 5 6]


In [17]:
#join and split in 1d array
array_1 = np.array([1,2,3,4,5,6])
array_2 = np.array([21,3,4,28,24,6])
#concatenate
print("concatenating array 1 and array 2 using concatenate:",np.concatenate((array_1,array_2)))
#stack
print("concatenating array 1 and array 2 using stack:",np.stack((array_1,array_2),axis=1)) #dstack : merging based on height
#split
print("splitting array_1 :", np.array_split(array_1,4))

concatenating array 1 and array 2 using concatenate: [ 1  2  3  4  5  6 21  3  4 28 24  6]
concatenating array 1 and array 2 using stack: [[ 1 21]
 [ 2  3]
 [ 3  4]
 [ 4 28]
 [ 5 24]
 [ 6  6]]
splitting array_1 : [array([1, 2]), array([3, 4]), array([5]), array([6])]


In [35]:
#join and split in 2d array
array_2d1 = np.array([[1,2,3],[4,5,6]])
array_2d2 = np.array([[21,24,28],[4,3,6]])
#concatenate
print("concatenating array 1 and array 2 using concatenate:",np.concatenate((array_2d1,array_2d2),axis =1)) #along row
#stack
print("concatenating array 1 and array 2 using stack:",np.stack((array_2d1,array_2d2),axis=1)) #dstack : merging based on height
#split
print("splitting array_1 :", np.array_split(array_2d1,2))




concatenating array 1 and array 2 using concatenate: [[ 1  2  3 21 24 28]
 [ 4  5  6  4  3  6]]
concatenating array 1 and array 2 using stack: [[[ 1  2  3]
  [21 24 28]]

 [[ 4  5  6]
  [ 4  3  6]]]
splitting array_1 : [array([[1, 2, 3]]), array([[4, 5, 6]])]


In [81]:
import random
#functions in NumPy array
#search function
fun_arr = np.array([21,4,24,28,3,6])
x1=np.where(fun_arr%2==0)
print("using where function:",x1)
#searchsort
x2 = np.searchsorted(fun_arr,24)
print("using searchsort function:",x2)
#sort
x3 = np.sort(fun_arr)
print("using sort function:",x3)
#filter
x4 = [True,False,True,True,False,False]
filter_array = fun_arr[x4]
print("using filter function:",filter_array)
#shuffle
random_arr = np.array([1,7,3,4,8,6,5])
np.random.shuffle(random_arr)
print("using shuffle function:",random_arr)
#unique
x5=np.unique(fun_arr,return_index=True,return_counts=True)
print("using unique function:",x5)
#resize
x6 = np.resize(fun_arr,(3,2))
print("using resize function:",x6)
#flatten and ravel
fun_arr2d = np.array([[1,2,3],[4,5,6]])
x7 = fun_arr2d.flatten(order="F") #fortran style:column major
print("using flatten function:",x7)
x8=np.ravel(fun_arr2d,order="K")
print("using ravel function:",x8)




using where function: (array([1, 2, 3, 5], dtype=int64),)
using searchsort function: 2
using sort function: [ 3  4  6 21 24 28]
using filter function: [21 24 28]
using shuffle function: [8 1 4 5 7 6 3]
using unique function: (array([ 3,  4,  6, 21, 24, 28]), array([4, 1, 5, 0, 2, 3], dtype=int64), array([1, 1, 1, 1, 1, 1], dtype=int64))
using resize function: [[21  4]
 [24 28]
 [ 3  6]]
using flatten function: [1 4 2 5 3 6]
using ravel function: [1 2 3 4 5 6]


In [123]:
#insert and delete in NumPy
var1 = np.array([1,2,3,4,5,6])
var1_2d = np.array([[1,2,3],[4,5,6]])
print("1d array:",var1)
print("2d array:",var1_2d)
x1=np.insert(var1,(0,4),28) #new array is created no change in var1
print("new array x1 using var1:",x1)
print("printing var1 after insert function:",var1)
x2 = np.insert(var1_2d,(0,1),(24,28),axis=1)
print(x2)
x3=np.append(var1,6.5)
print("using append function:",x3)
x4=np.delete(var1,2)
print("using delete function on var1:",x4)
x5=np.delete(var1_2d,(0,2),axis=1)
print("using delete function on var1_2d:",x5)


1d array: [1 2 3 4 5 6]
2d array: [[1 2 3]
 [4 5 6]]
new array x1 using var1: [28  1  2  3  4 28  5  6]
printing var1 after insert function: [1 2 3 4 5 6]
[[24  1 28  2  3]
 [24  4 28  5  6]]
using append function: [1.  2.  3.  4.  5.  6.  6.5]
using delete function on var1: [1 2 4 5 6]
using delete function on var1_2d: [[2]
 [5]]


In [145]:
#matrix function
mat1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.matrix([[21,4,3],[28,24,6],[47,14,9]])
mat3 = np.matrix([[1,2],[3,4]])
print("matrix1:",mat1)
print("matrix2:",mat2)
print("addition of matrix:",np.add(mat1,mat2))
mul_mat=mat1.dot(mat2)
print("multiplication of matrix:",mul_mat)
#matrix functions
#transpose and swapaxes
print("using transpose function on mat1:",np.transpose(mat1))
print("transposing mat2 using second method:",mat2.T)
print("using swapaxes on mat1:",np.swapaxes(mat1,0,1))
#determinant
print("finding determinant:",np.linalg.det(mat3))
#inverse
print("using inverse function:",np.linalg.inv(mat3))
#power
print("finding power:",np.linalg.matrix_power(mat3,n=2))


matrix1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix2: [[21  4  3]
 [28 24  6]
 [47 14  9]]
addition of matrix: [[22  6  6]
 [32 29 12]
 [54 22 18]]
multiplication of matrix: [[218  94  42]
 [506 220  96]
 [794 346 150]]
using transpose function on mat1: [[1 4 7]
 [2 5 8]
 [3 6 9]]
transposing mat2 using second method: [[21 28 47]
 [ 4 24 14]
 [ 3  6  9]]
using swapaxes on mat1: [[1 4 7]
 [2 5 8]
 [3 6 9]]
finding determinant: -2.0000000000000004
using inverse function: [[-2.   1. ]
 [ 1.5 -0.5]]
finding power: [[ 7 10]
 [15 22]]
