In [21]:
#Creating NumPy Arrays - simplest method
import numpy as np
var1 = np.array([1,2,3,4,5])
print(var1)
print("Dimeesion of var1 array:",var1.ndim,"dimeesional")


[1 2 3 4 5]
Dimeesion of var1 array: 1 dimeesional


In [7]:
#creating NumPy array using for loop
l=[]
t = int(input("enter total elements in array")) #elements in array
for i in range(0,t):
    item = int(input("enter:"))
    l.append(item)
var2 = np.array(l)
print("Array created:" , var2)


enter total elements in array 6
enter: 28
enter: 24
enter: 4
enter: 6
enter: 3
enter: 24


Array created: [28 24  4  6  3 24]


In [19]:
#creating multi-dimenssional array
mul_var =np.array([[[[1,2,3,4],[2,4,5,6],[7,8,3,9]]]])
print(mul_var)
print("Dimession of mul_var:",mul_var.ndim)


[[[[1 2 3 4]
   [2 4 5 6]
   [7 8 3 9]]]]
Dimession of mul_var: 4


In [45]:
#creating zeroArray ,onesArray , emptyArray
var3 = np.zeros((3,5))
print("Zero Array:",var3)
var4 = np.ones(4)
print("One Array:",var4)
var5 = np.empty(2) #takes garbage value
print("Empty Array:",var5)

Zero Array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
One Array: [1. 1. 1. 1.]
Empty Array: [5.89000796e-245 1.83277370e+208]


In [63]:
#using arange function
avar = np.arange(10)
print(avar)

[0 1 2 3 4 5 6 7 8 9]


In [71]:
#filling Diagonal elements with 1(s)
var_diag = np.eye(5)
print("square matrix needs only 1 parameter:",var_diag)
print(var_diag.ndim)
var_diag1 = np.eye(2,7)
print(var_diag1)

square matrix needs only 1 parameter: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]


In [85]:
#using random module in NumPy
#1.rand function
rvar = np.random.rand(5)
print("Array using rand() function:",rvar)
#2.randn function
rvar1 = np.random.randn(3)
print("Array using randn() function:",rvar1)
#3.ranf function
rvar2 = np.random.ranf(4)
print("Array using ranf() function:",rvar2)
#4.randint function
rvar3 = np.random.randint(21,29,6)
print("Array using randint() function:",rvar3)


Array using rand() function: [0.61610689 0.21646157 0.30206839 0.16792629 0.56606345]
Array using randn() function: [-0.05864926  1.29090321 -0.2923671 ]
Array using ranf() function: [0.43772661 0.57548792 0.40380833 0.99540217]
Array using randint() function: [27 28 24 23 22 24]


In [111]:
#datatype in NumPy
d_var = np.arange(5.0)
print(d_var.dtype)

s_var = np.array(["div", "riyu" ,"harshit"])
print("string array:",s_var)
print(s_var.dtype)

#changing datatype of array
#method1
d_var1 = np.array([21,24,28,4,3], np.int16)
print(d_var1,"\nDatatype of d_var1:",d_var1.dtype)
#method2
new = np.float16(d_var1)
print(new)
print(new.dtype)
print(d_var1.dtype) #datatype of d_var1 does not change , "new" named array is created



float64
string array: ['div' 'riyu' 'harshit']
<U7
[21 24 28  4  3] 
Datatype of d_var1: int16
[21. 24. 28.  4.  3.]
float16
int16
