In [5]:
#NumPy Arithematic operation 
import numpy as np
array_1 = np.array([21,24,28])
array_2 = np.array([3,4,6])
print("Addition of two arrays:",np.add(array_1,array_2))
print("Subtraction of two arrays:",np.subtract(array_1,array_2))
print("Multiplication of two arrays:",np.multiply(array_1,array_2))
print("Divison of two arrays:",np.divide(array_1,array_2))
print("Modulas of two arrays:",np.mod(array_1,array_2))
print("Power of two arrays:",np.power(array_1,array_2))
print("Reciprocal of the array:",np.reciprocal(array_1))


Addition of two arrays: [24 28 34]
Subtraction of two arrays: [18 20 22]
Multiplication of two arrays: [ 63  96 168]
Divison of two arrays: [7.         6.         4.66666667]
Modulas of two arrays: [0 0 4]
Power of two arrays: [     9261    331776 481890304]
Reciprocal of the array: [0 0 0]


In [9]:
#NumPy Arithematic Function
array_3 = np.array([21,24,28,3,4,6])
print("Minimum value in array:",np.min(array_3))
print("Maximum value in array:",np.max(array_3))
print("Minimum value index in array:",np.argmin(array_3))
print("Maximum value index in array:",np.argmax(array_3))
print("Cummulative sum of array:",np.cumsum([1, 2, 3]))
print("Square root of array:",np.sqrt(array_3))
print("Sin of array:",np.sin(array_3))
print("Cos of array:",np.cos(array_3))


Minimum value in array: 3
Maximum value in array: 28
Minimum value index in array: 3
Maximum value index in array: 2
Cummulative sum of array: [1 3 6]
Square root of array: [4.58257569 4.89897949 5.29150262 1.73205081 2.         2.44948974]
Sin of array: [ 0.83665564 -0.90557836  0.27090579  0.14112001 -0.7568025  -0.2794155 ]
Cos of array: [-0.54772926  0.42417901 -0.96260587 -0.9899925  -0.65364362  0.96017029]


In [11]:
#operating on 2d array
array_2d = np.array([[21,24,28],[4,3,6]])
print("Minimum value in array:",np.min(array_2d,axis=0))
print("Minimum value in array:",np.min(array_2d,axis=1))


Minimum value in array: [4 3 6]
Minimum value in array: [21  3]


In [19]:
#Shaping and Reshaping in NumPy
#1D array
array_4 = np.array([21,24,28,3,4,6])
print(array_4.shape)
#2D array
array_2d =  np.array([[21,24,28],[4,3,6]])
print(array_2d.shape)

new = array_4.reshape(3,2)
print(new)

print(new.reshape(-1))


(6,)
(2, 3)
[[21 24]
 [28  3]
 [ 4  6]]
[21 24 28  3  4  6]


In [21]:
#broadcasting In NumPy
array_1 = np.array([[1,2,3]])
array_2 = np.array([[1],[2],[3]])
print("Addition of two different dimenssion aaray:",np.add(array_1,array_2))

Addition of two different dimenssion aaray: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [23]:
#Iterating NumPy array
array_2d = np.array([[21,24,28],[4,6,3]])
#nditer function
print("Iterating using nditer function:")
for i in np.nditer(array_2d):
    print(i)
#ndenumerate function
print("Iterating using ndenumerate function:")
for j,d in np.ndenumerate(array_2d):
    print(j,d)


Iterating using nditer function:
21
24
28
4
6
3
Iterating using ndenumerate function:
(0, 0) 21
(0, 1) 24
(0, 2) 28
(1, 0) 4
(1, 1) 6
(1, 2) 3
